/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BaseNode: typeof import('./src/components/BaseNode.vue')['default']
    ComponentNode: typeof import('./src/components/ComponentNode.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    RootNode: typeof import('./src/components/RootNode.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SiloNode: typeof import('./src/components/SiloNode.vue')['default']
  }
}
